2020-06-26 20:28:40,530 (112295/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:28:40,530 (112295/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:28:40,534 (112295/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/coutinho/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "coutinho" does not exist\n\n'
2020-06-26 20:28:49,202 (112411/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:28:49,202 (112411/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:29:10,890 (112411/MainThread) pgcli.pgexecute ERROR - sql: 'show db', error: UndefinedObject('unrecognized configuration parameter "db"\n')
2020-06-26 20:29:10,891 (112411/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "db"\n\n'
2020-06-26 20:29:43,136 (112877/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:29:43,136 (112877/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:29:54,873 (112877/MainThread) pgcli.pgexecute ERROR - sql: 'show ta', error: UndefinedObject('unrecognized configuration parameter "ta"\n')
2020-06-26 20:29:54,873 (112877/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "ta"\n\n'
2020-06-26 20:29:58,117 (112877/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2020-06-26 20:29:58,117 (112877/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2020-06-26 20:30:01,625 (112877/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2020-06-26 20:30:01,626 (112877/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2020-06-26 20:35:55,145 (115869/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:35:55,145 (115869/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:36:33,695 (115869/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE test', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n')
2020-06-26 20:36:33,696 (115869/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n\n'
2020-06-26 20:36:38,015 (115869/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE test', error: SyntaxError('syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n')
2020-06-26 20:36:38,015 (115869/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: CREATE TABLE test\n                         ^\n\n'
2020-06-26 20:37:14,368 (115869/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^\n')
2020-06-26 20:37:14,368 (115869/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n\n'
2020-06-26 20:46:04,102 (119967/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:46:04,102 (119967/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:48:49,686 (121236/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:48:49,686 (121236/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:48:49,689 (121236/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/coutinho/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "coutinho" does not exist\n\n'
2020-06-26 20:48:55,053 (121298/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:48:55,053 (121298/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:48:55,056 (121298/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/coutinho/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "admin" does not exist\n\n'
2020-06-26 20:51:47,400 (123112/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 20:51:47,400 (123112/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 20:51:51,123 (123112/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^\n')
2020-06-26 20:51:51,124 (123112/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n\n'
2020-06-26 20:54:06,967 (123112/MainThread) pgcli.pgexecute ERROR - sql: "INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) VALUES (1, 'Paul', 32, 'California', 20000.00,'2001-07-13')", error: UndefinedColumn('column "join_date" of relation "company" does not exist\nLINE 1: INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) V...\n                                                        ^\n')
2020-06-26 20:54:06,967 (123112/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "join_date" of relation "company" does not exist\nLINE 1: INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) V...\n                                                        ^\n\n'
2020-06-26 22:22:28,301 (4199/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 22:22:28,305 (4199/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 22:23:48,789 (4199/MainThread) pgcli.pgexecute ERROR - sql: "INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (2, 'Zunil', 32, 'California', 20000.00,'2001-07-13')", error: SyntaxError("INSERT has more expressions than target columns\nLINE 1: ...Y) VALUES (2, 'Zunil', 32, 'California', 20000.00,'2001-07-1...\n                                                             ^\n")
2020-06-26 22:23:48,792 (4199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: INSERT has more expressions than target columns\nLINE 1: ...Y) VALUES (2, \'Zunil\', 32, \'California\', 20000.00,\'2001-07-1...\n                                                             ^\n\n'
2020-06-26 22:23:59,144 (4199/MainThread) pgcli.pgexecute ERROR - sql: "INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) VALUES (2, 'Zunil', 32, 'California', 20000.00,)", error: SyntaxError('syntax error at or near ")"\nLINE 1: ...ESS,SALARY) VALUES (2, \'Zunil\', 32, \'California\', 20000.00,)\n                                                                      ^\n')
2020-06-26 22:23:59,144 (4199/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ")"\nLINE 1: ...ESS,SALARY) VALUES (2, \'Zunil\', 32, \'California\', 20000.00,)\n                                                                      ^\n\n'
2020-06-26 22:24:50,574 (5501/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 22:24:50,574 (5501/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 22:24:50,671 (5501/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/coutinho/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-06-26 22:25:36,533 (6500/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 22:25:36,533 (6500/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 22:25:42,758 (6500/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^\n')
2020-06-26 22:25:42,759 (6500/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n\n'
2020-06-26 22:29:42,728 (8492/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 22:29:42,728 (8492/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-26 22:50:05,074 (17069/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-26 22:50:05,074 (17069/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-27 10:32:23,687 (3007/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-27 10:32:23,695 (3007/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-06-27 11:07:53,620 (21002/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-06-27 11:07:53,621 (21002/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-06 11:59:55,516 (25105/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-06 11:59:55,545 (25105/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-06 12:00:29,300 (25375/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-06 12:00:29,300 (25375/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-06 12:00:29,400 (25375/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/coutinho/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "myDB" does not exist\n\n'
2020-07-19 21:10:27,204 (1528/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-19 21:10:27,233 (1528/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-19 21:10:27,325 (1528/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/coutinho/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "myDB" does not exist\n\n'
